;; Lists invalid frontend fixtures and the diagnostics each must produce.

(("bad-input-drive.rhdl" "connection target must be a driveable hardware place")
 ("bad-valid-event-stalls.rhdl" "does not expect an argument with given keyword")
 ("bad-bundle-update-duplicate.rhdl" "duplicate keyword")
 ("bad-bundle-update-drive.rhdl" "connection target must be a driveable hardware place")
 ("bad-instance-combinational-cycle.rhdl" "combinational cycle reaches value u.y")
 ("bad-instance-port.rhdl" "instance u has no port or interface named missing")
 ("bad-interface-directions.rhdl" "incompatible roles and boundary directions")
 ("bad-interface-member-type.rhdl" "interface member type must be a DataType or InterfaceType")
 ("bad-interface-provider-role.rhdl" "provider role must be one of the declared roles")
 ("bad-interface-role.rhdl" "unknown interface role observer")
 ("bad-interface-support-role.rhdl" "contract role must match the provider role")
 ("bad-interface-specialization-compatibility.rhdl" "does not support")
 ("bad-interface-specialization-shape.rhdl" "exactly the same wire shape")
 ("bad-interface-compatibility-result.rhdl" "must return a host Boolean")
 ("bad-interface-exact-specialization.rhdl" "argument does not satisfy annotation")
 ("bad-interface-equal-specialization-compatibility.rhdl" "does not support")
 ("bad-interface-monitor-drive.rhdl" "connection target must be a driveable hardware place")
 ("bad-interface-type.rhdl" "does not support")
 ("bad-interface-array-zero.rhdl" "PosInt")
 ("bad-interface-array-count.rhdl" "PosInt")
 ("bad-interface-array-index.rhdl" "Nat")
 ("bad-interface-array-duplicate.rhdl" "duplicate interface endpoint")
 ("bad-interface-array-length.rhdl" "must have the same length")
 ("bad-interface-array-type.rhdl" "does not support")
 ("bad-interface-array-role.rhdl" "incompatible roles and boundary directions")
 ("bad-mux-key-type.rhdl" "mux lookup keys must be host natural numbers")
 ("bad-mux-key-width.rhdl" "mux lookup key does not fit its selector type")
 ("bad-mux-duplicate-key.rhdl" "mux lookup keys must be unique")
 ("bad-switch-empty.rhdl" "switch requires at least one case")
 ("bad-switch-case-after-otherwise.rhdl" "switch case cannot follow otherwise")
 ("bad-parameter.rhdl" "circuit parameter 0 must be a host value, not live hardware")
 ("bad-register-parameter.rhdl" "circuit parameter 0 must be a host value, not live hardware")
 ("bad-ambient-register.rhdl" "implicit clock/reset use requires an active sync_circuit")
 ("bad-assert-host-condition.rhdl" "expected readable hardware data")
 ("bad-assert-wide-condition.rhdl" "assert condition must be a one-bit ScalarDataType")
 ("bad-assert-partial-domain.rhdl" "explicit assertions require both ~clock and ~reset")
 ("bad-assert-outside-sync.rhdl" "implicit clock/reset use requires an active sync_circuit")
 ("bad-enum-encoding.rhdl" "variant encodings must be unique")
 ("bad-enum-width.rhdl" "variant encoding does not fit the declared width")
 ("bad-enum-assignment.rhdl" "connection source and target must have exactly the same hardware type")
 ("bad-enum-equality.rhdl" "=== operands must have exactly the same ScalarDataType")
 ("bad-enum-inequality.rhdl" "=/= operands must have exactly the same ScalarDataType")
 ("bad-is-one-of-bundle.rhdl" ".is_one_of subject must have a ScalarDataType")
 ("bad-is-one-of.rhdl" ".is_one_of operands must have exactly the same ScalarDataType")
 ("bad-zext-receiver.rhdl" ".zext receiver must have a Bits type")
 ("bad-sext-receiver.rhdl" ".sext receiver must have a SignedArithmeticType")
 ("bad-or-reduce-type.rhdl" "or_reduce operand must have a packable DataType")
 ("bad-or-reduce-list-type.rhdl" "or_reduce list elements must have packable DataTypes")
 ("bad-and-reduce-type.rhdl" "and_reduce operand must have a packable DataType")
 ("bad-popcount-type.rhdl" "popcount operand must have a packable DataType")
 ("bad-priority-encoder-type.rhdl" "priority_encoder operand must have a packable DataType")
 ("bad-priority-encoder-oh-type.rhdl" "priority_encoder_oh operand must have a packable DataType")
 ("bad-invert-enum.rhdl" "bit_not operand must have a bitwise type")
 ("bad-enum-member.rhdl" "enum State has no member named Missing")
 ("bad-enum-mux-integer-key.rhdl" "enum mux lookup keys must be members of the selector's enum type")
 ("bad-enum-mux-foreign-key.rhdl" "enum mux lookup keys must be members of the selector's enum type")
 ("bad-enum-mux-duplicate-key.rhdl" "mux lookup keys must be unique")
 ("bad-one-hot-enum-mux-missing.rhdl" "keyed mux arms must cover every one-hot selector lane exactly once")
 ("bad-one-hot-enum-mux-unknown.rhdl" "enum mux lookup keys must be members of the selector's enum type")
 ("bad-bundle-method-collision.rhdl" "bundle fields and methods must have distinct names")
 ("bad-sync-parent.rhdl" "implicit clock/reset use requires an active sync_circuit")
 ("bad-sync-partial-override.rhdl" "explicit sync child wiring requires both clock and reset")
 ("bad-sync-foreign-clock.rhdl" "explicit clock/reset controls are not allowed inside sync_circuit")
 ("bad-sync-child-foreign-clock.rhdl" "explicit clock/reset controls are not allowed inside sync_circuit")
 ("bad-sync-clock-reference.rhdl" "clock: unbound identifier")
 ("bad-sync-reset-reference.rhdl" "reset: unbound identifier")
 ("bad-reset-when-outside-sync.rhdl" "implicit clock/reset use requires an active sync_circuit")
 ("bad-reset-when-wide.rhdl" "reset_when condition must be readable one-bit data or Reset")
 ("bad-reset-active-outside-sync.rhdl" "implicit clock/reset use requires an active sync_circuit")
 ("bad-reset-when-ordinary-child.rhdl" "~reset_when requires a sync_circuit child")
 ("bad-sync-memory-explicit-clock.rhdl" "explicit clock/reset controls are not allowed inside sync_circuit")
 ("bad-sync-write-explicit-clock.rhdl" "explicit clock/reset controls are not allowed inside sync_circuit")
 ("bad-sync-assert-explicit-domain.rhdl" "explicit clock/reset controls are not allowed inside sync_circuit")
 ("bad-sync-dpi-explicit-clock.rhdl" "explicit clock/reset controls are not allowed inside sync_circuit")
 ("bad-clocking-without-wrapper.rhdl" "clocking declarations require elaborate_with_clocking")
 ("bad-clocking-child-declaration.rhdl" "clocking environment declarations must belong to the elaborated top circuit")
 ("bad-clocking-output-contract.rhdl" "input timing declaration must reference a readable hardware value")
 ("bad-clocking-conditional.rhdl" "input timing declaration is not supported inside when")
 ("bad-clocking-duplicate-relationship.rhdl" "environment contains a duplicate clock relationship")
 ("bad-interface-parameter.rhdl" "circuit parameter 0 must be a host value, not live hardware")
 ("bad-recursion.rhdl" "recursive elaboration of circuit Recursive")
 ("bad-nested-circuit-capture.rhdl" "hardware value belongs to a different module")
 ("bad-nested-circuit-sync-inherit.rhdl" "implicit clock/reset use requires an active sync_circuit")
 ("bad-top-call.rhdl" "circuit generators may only be called during elaborate")
 ("bad-width.rhdl" "add operands must have exactly the same arithmetic type and width")
 ("bad-expanding-arithmetic-type.rhdl" "expanding arithmetic operands must be Bits")
 ("bad-expanding-arithmetic-mixed.rhdl" "expanding multiplication operands must both be Bits or signed arithmetic values")
 ("bad-unsigned-comparison-width.rhdl" "unsigned comparison operands must have exactly the same Bits width")
 ("bad-unsigned-comparison-type.rhdl" "unsigned comparison operands must have exactly the same Bits width")
 ("bad-shift-amount.rhdl" "shift amount must be Bits")
 ("bad-signed-width.rhdl" "same arithmetic type and width")
 ("bad-signed-mixed-type.rhdl" "same arithmetic type and width")
 ("bad-signed-comparison.rhdl" "same signed arithmetic type and width")
 ("bad-signed-literal.rhdl" "fit the declared signed width")
 ("bad-signed-shift-amount.rhdl" "shift amount must be Bits")
 ("base-core-leak.rhdl" "Design: unbound identifier")
 ("base-kernel-leak.rhdl" "run_elaboration: unbound identifier")
 ("base-kernel-port-leak.rhdl" "input: misuse as an expression")
 ("base-layer-leak.rhdl" "Mask: unbound identifier")
 ("default-core-leak.rhdl" "Design: unbound identifier")
 ("default-kernel-leak.rhdl" "run_elaboration: unbound identifier")
 ("base-enum-leak.rhdl" "hardware_enum: unbound identifier")
 ("base-assertion-leak.rhdl" "assert: unbound identifier")
 ("base-sync-leak.rhdl" "sync_circuit: unbound identifier"))
