// Declares the generated-SystemVerilog ABI for the Spike execution model.
// SPDX-License-Identifier: Apache-2.0
#pragma once

#include <svdpi.h>

extern "C" unsigned char rhodium_spike_tick(
    unsigned char reset, long long hart_id, long long reset_vector,
    long long time, char interrupts, unsigned char xlen_is_64,
    char max_vaddr_bits, int vector_length, int vector_element_width,
    const svBitVecVal* isa, int privilege,
    short max_retired_instructions_per_cycle, char pmp_regions,
    short instruction_cache_sets, short instruction_cache_ways,
    short data_cache_sets, short data_cache_ways,
    unsigned char address_request_ready,
    unsigned char address_response_valid,
    unsigned char address_response_cacheable,
    unsigned char address_response_cache_block_zero,
    unsigned char address_response_instruction_cacheable,
    unsigned char address_response_device,
    unsigned char address_response_atomic,
    unsigned char address_response_fault,
    unsigned char instruction_request_ready,
    unsigned char instruction_response_valid,
    const svBitVecVal* instruction_response_line,
    unsigned char instruction_response_fault,
    unsigned char acquire_request_ready,
    unsigned char acquire_response_valid,
    const svBitVecVal* acquire_response_line,
    char acquire_response_state,
    unsigned char acquire_response_pass_dirty,
    unsigned char acquire_response_fault,
    unsigned char release_request_ready,
    unsigned char release_response_valid,
    unsigned char release_response_fault,
    unsigned char snoop_valid, long long snoop_address,
    unsigned char snoop_share, unsigned char snoop_invalidate,
    unsigned char snoop_discard_dirty,
    unsigned char snoop_return_to_source,
    unsigned char snoop_response_ready,
    unsigned char uncached_request_ready,
    unsigned char uncached_response_valid,
    long long uncached_response_data,
    unsigned char uncached_response_fault,
    unsigned char* address_request_valid,
    long long* address_request_address,
    char* address_request_size,
    unsigned char* address_request_write,
    unsigned char* address_request_execute,
    unsigned char* address_response_ready,
    unsigned char* instruction_request_valid,
    long long* instruction_request_address,
    unsigned char* instruction_response_ready,
    unsigned char* acquire_request_valid,
    long long* acquire_request_address,
    unsigned char* acquire_request_unique,
    unsigned char* acquire_response_ready,
    unsigned char* release_request_valid,
    long long* release_request_address,
    svBitVecVal* release_request_line,
    char* release_request_state,
    unsigned char* release_response_ready,
    unsigned char* snoop_ready,
    unsigned char* snoop_response_valid,
    char* snoop_response_state,
    unsigned char* snoop_response_pass_dirty,
    unsigned char* snoop_response_has_data,
    svBitVecVal* snoop_response_line,
    unsigned char* uncached_request_valid,
    long long* uncached_request_address,
    unsigned char* uncached_request_write,
    char* uncached_request_size,
    long long* uncached_request_data,
    char* uncached_request_mask,
    unsigned char* uncached_request_device);
