# Hardens the Rhodium inverter in a compact, tap-filled block for reproducible LVS.
# SPDX-License-Identifier: Apache-2.0

DESIGN_NAME: rhodium_lvs_smoke
VERILOG_FILES:
  - dir::../../build/rhodium-top.sv
  - dir::../../verilog/rtl/rhodium_lvs_smoke.v

meta:
  version: 3
  flow: Classic

CLOCK_PORT: null
CLOCK_PERIOD: 10
RUN_CTS: false

FP_SIZING: absolute
DIE_AREA: [0, 0, 100, 100]
CORE_AREA: [10, 10, 90, 90]
PL_TARGET_DENSITY_PCT: 5

VDD_NETS: [vccd1]
GND_NETS: [vssd1]
PDN_MULTILAYER: true
PDN_VPITCH: 40
PDN_HPITCH: 40
PDN_CORE_RING: false

RUN_TAP_ENDCAP_INSERTION: true
RUN_FILL_INSERTION: true
RUN_LVS: true
RUN_IRDROP_REPORT: false

MAGIC_EXT_UNIQUE: notopports
PRIMARY_GDSII_STREAMOUT_TOOL: klayout
