# Catalogues Sky130 SRAM geometry, interfaces, functional models, and physical collateral.
# SPDX-License-Identifier: Apache-2.0

[macro:sky130_sram_2kbyte_1rw1r_32x512_8]
name = sky130_sram_2kbyte_1rw1r_32x512_8
interface = openram_1rw1r
depth = 512
width = 32
write_granularity = 8
address_width = 9
read_ports = 1
read_write_ports = 1
width_um = 683.1
height_um = 416.54
power_pins = vccd1, vssd1
functional_verilog = models/sky130_sram_2kbyte_1rw1r_32x512_8.functional.sv
verilog = libs.ref/sky130_sram_macros/verilog/sky130_sram_2kbyte_1rw1r_32x512_8.v
lef = libs.ref/sky130_sram_macros/lef/sky130_sram_2kbyte_1rw1r_32x512_8.lef
gds = libs.ref/sky130_sram_macros/gds/sky130_sram_2kbyte_1rw1r_32x512_8.gds
liberty = libs.ref/sky130_sram_macros/lib/sky130_sram_2kbyte_1rw1r_32x512_8_TT_1p8V_25C.lib
spice = libs.ref/sky130_sram_macros/spice/sky130_sram_2kbyte_1rw1r_32x512_8.spice
